Audits:
  Avg Ball Time: 0:00
  Avg Extra Balls: 0
  Avg Game Time: 0:00
  Avg Score: 0
  Games Played: 0
  Games Started: 0
  Balls Played: 0
ClassicHighScores:
  - {inits: GSS, score: 500}
  - {inits: ASP, score: 400}
  - {inits: JRP, score: 300}
  - {inits: JAG, score: 200}
  - {inits: JTW, score: 100}
LoopsHighScoreData:
  - {inits: GSS, score: 5}
