# P-ROC Game Description file for Judge Dredd
PRGame:
    machineType: wpc
    numBalls: 6
PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpR
    - flipperUpL
PRBumpers:
    - slingL
    - slingR
PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #                  'NC' (normally closed.  Common for optos)
    flipperLwR:
        number: SF2
    flipperLwL:
        number: SF4
    flipperUpR:
        number: SF6
    flipperUpL:
        number: SF8
    exit:
        number: SD5
    down:
        number: SD6
    up:
        number: SD7
    enter:
        number: SD8
    fireL:
        number: S11
    fireR:
        number: S12
    startButton:
        number: S13
    tilt:
        number: S14
    shooterL:
        number: S15
    outlaneL:
        number: S16
    inlaneL:
        number: S17
    threeBankTargets:
        number: S18
    slamTilt:
        number: S21
    coinDoor:
        number: S22
    ticketDispenser:
        number: S23
    alwaysClosed:
        number: S24
    rightTopPost:
        number: S25
    captiveBall1:
        number: S26
    mystery:
        number: S27
    ballOnMagnet:
        number: S28
    buyIn:
        number: S31
    leftRampEnter:
        number: S32
        type: 'NC'
    leftRollover:
        number: S33
    inlaneR:
        number: S34
    topCenterRollover:
        number: S35
    leftScorePost:
        number: S36
    subwayEnter1:
        number: S37
    subwayEnter2:
        number: S38
    shooterR:
        number: S41
        tags: shooter
    outlaneR:
        number: S42
    inlaneFarR:
        number: S43
    superGame:
        number: S44
    s45:
        number: S45
    s46:
        number: S46
    s47:
        number: S47
    s48:
        number: S48
    slingL:
        number: S51
    slingR:
        number: S52
    captiveBall2:
        number: S53
    dropTargetJ:
        number: S54
        type: 'NC'
    dropTargetU:
        number: S55
        type: 'NC'
    dropTargetD:
        number: S56
        type: 'NC'
    dropTargetG:
        number: S57
        type: 'NC'
    dropTargetE:
        number: S58
        type: 'NC'
    globePosition1:
        number: S61
        type: 'NO' # Manual says NC
    craneRelease:
        number: S62
        type: 'NC'
    leftRampToLock:
        number: S63
        type: 'NC'
    leftRampExit:
        number: S64
        type: 'NC'
    rightRampEnter:
        number: S65
        type: 'NC'
    centerRampExit:
        number: S66
        type: 'NC'
    leftRampEnterAlt:
        number: S67
        type: 'NC'
    captiveBall3:
        number: S68
    magnetOverRing:
        number: S71
        type: 'NO' # Manual says NC
    topRightOpto:
        number: S72
        type: 'NC'
    popperL:
        number: S73
        type: 'NC'
    popperR:
        number: S74
        type: 'NC'
    topRampExit:
        number: S75
        type: 'NC'
    rightRampExit:
        number: S76
        type: 'NC'
    globePosition2:
        number: S77
        type: 'NO' # Manual says NC
    s78:
        number: S78
    trough1:
        number: S81
        type: 'NC'
        tags: trough
    trough2:
        number: S82
        type: 'NC'
        tags: trough
    trough3:
        number: S83
        type: 'NC'
        tags: trough
    trough4:
        number: S84
        type: 'NC'
        tags: trough
    trough5:
        number: S85
        type: 'NC'
        tags: trough
    trough6:
        number: S86
        type: 'NC'
        tags: trough
    troughTop:
        number: S87
        type: 'NC'
    s88:
        number: S88
PRCoils:
    flipperLwRMain:
        number: FLRM
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
    flipperLwLHold:
        number: FLLH
    flipperUpRMain:
        number: FURM
    flipperUpRHold:
        number: FURH
    flipperUpLMain:
        number: FULM
    flipperUpLHold:
        number: FULH
    craneMagnet:
        number: C01
    popperL:
        number: C02
    popperR:
        number: C03
    crane:
        number: C04
    resetDropTarget:
        number: C05
    globeMotor:
        number: C06
    knocker:
        number: C07
    shooterR:
        number: C08
        # the label here corresponds to putting the entry in the config/game_default_settings.yaml
        # together, this coil's strength will be able to be set by the user in the Service Mode->Coils Settings screen
        label: Auto Plunger
    shooterL:
        number: C09
    tripDropTarget:
        number: C10
    diverter:
        number: C11
    trough:
        number: C13
    slingL:
        number: C15
    slingR:
        number: C16
    flasherFire:
        number: C17
    flasherFear:
        number: C18
    flasherDeath:
        number: C19
    flasherMortis:
        number: C20
    flasherPursuitL:
        number: C21
    flasherPursuitR:
        number: C22
    flasherBlackout:
        number: C23
    flasherCursedEarth:
        number: C24
    flashersLowerLeft:
        number: C25
    flasherGlobe:
        number: C26
    flashersRtRamp:
        number: C27
    flashersInsert:
        number: C28
PRLamps:
    perp1W:
        number: L11
    perp1R:
        number: L12
    perp1Y:
        number: L13
    perp1G:
        number: L14
    perp2W:
        number: L15
    perp2R:
        number: L16
    perp2Y:
        number: L17
    perp2G:
        number: L18
    perp4W:
        number: L21
    perp4R:
        number: L22
    perp4Y:
        number: L23
    perp4G:
        number: L24
    perp5W:
        number: L25
    perp5R:
        number: L26
    perp5Y:
        number: L27
    perp5G:
        number: L28
    perp3W:
        number: L31
    perp3R:
        number: L32
    perp3Y:
        number: L33
    perp3G:
        number: L34
    lock1:
        number: L35
    lock2:
        number: L36
    lock3:
        number: L37
    superGame:
        number: L38
    crimeLevel4:
        number: L41
    crimeLevel3:
        number: L42
    crimeLevel2:
        number: L43
    crimeLevel1:
        number: L44
    meltdown:
        number: L45
    impersonator:
        number: L46
    battleTank:
        number: L47
    stopMeltdown:
        number: L48
    stakeout:
        number: L51
    safecracker:
        number: L52
    pursuit:
        number: L53
    ultChallenge:
        number: L54
    manhunt:
        number: L55
    blackout:
        number: L56
    sniper:
        number: L57
    pickAPrize:
        number: L58
    extraBall2:
        number: L61
    rightStartFeature:
        number: L62
    tankCenter:
        number: L63
    awardSniper:
        number: L64
    airRade:
        number: L65
    leftCenterFeature:
        number: L66
    tankLeft:
        number: L67
    mystery:
        number: L68
    dropTargetJ:
        number: L71
    dropTargetU:
        number: L72
    dropTargetD:
        number: L73
    dropTargetG:
        number: L74
    dropTargetE:
        number: L75
    awardSafecracker:
        number: L76
    multiballJackpot:
        number: L77
    awardBadImpersonator:
        number: L78
    awardStakeout:
        number: L81
    blackoutJackpot:
        number: L82
    drainShield:
        number: L83
        tags: shoot_again
    judgeAgain:
        number: L84
    advanceCrimeLevel:
        number: L85
    tankRight:
        number: L86
    buyIn:
        number: L87
    startButton:
        number: L88
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05

PRBallSave:
    pulseCoils: [popperL, popperR, resetDropTarget,
                 shooterR, shooterL, slingL, slingR]
    resetSwitches:
        shooterL: open
        outlaneL: open
        inlaneL: open
        threeBankTargets: open
        rightTopPost: open
        captiveBall1: open
        mystery: open
        leftRampEnter: closed
        leftRollover: open
        inlaneR: open
        topCenterRollover: open
        leftScorePost: open
        subwayEnter1: open
        subwayEnter2: open
        shooterR: open
        outlaneR: open
        inlaneFarR: open
        slingL: open
        slingR: open
        captiveBall2: open
        dropTargetJ: open
        dropTargetU: open
        dropTargetD: open
        dropTargetG: open
        dropTargetE: open
        trough1: closed
        leftRampEnter: closed
        leftRampToLock: closed
        leftRampExit: closed
        rightRampEnter: closed
        centerRampExit: closed
        captiveBall3: open
        topRightOpto: closed
        topRampExit: closed
        rightRampExit: closed
        globePosition2: open
    stopSwitches:
        shooterR: closed
        shooterL: closed
        popperL: active
        popperR: active
        # don't ball search if a flipper button is pressed
        flipperLwL: closed
        flipperLwR: closed
